config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth_v2', as: :auth_v2
  resources :vehicles
  root to: 'welcome#index'
  post '/', to: 'profiles#search', as: :search_profile
  get '/generate_graphic', to: 'welcome#generate_graphic', as: :generate_graphic
  devise_for :users
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  def search
    broadcast_update_to(:results_from_model, target: 'results_from_model', partial: 'welcome/results',
                                             locals: { categories: Category.all })
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable
  include DeviseTokenAuth::Concerns::User
  before_create :skip_confirmation
  def self.authenticate(email, password)
    user = User.find_or_authentication(email: email)
    user&.valid_password?(password) ? user : nil
  end


  private

  def skip_confirmation
    self.confirmed_at = DateTime.now
  end
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  has_many_attached :images
  after_create :schedule_attach_watermark

  def schedule_attach_watermark
    # binding.pry

    ImageJob.perform_later(id)
  end

  def attach_watermark
    return if images.blank?

    new_images = []
    watermark = Magick::Image.read(Rails.root.join('app', 'assets', 'images', 'ruby.png').to_s).first
    watermark.resize_to_fit!(100, 100)
    images.each do |image|
      filename = File.basename(Faker::File.file_name(dir: nil, ext: 'png')).to_s
      tmp_file = Tempfile.new(filename, Rails.root.join('tmp').to_s)
      tmp_file.binmode
      tmp_file.write(image.download)
      tmp_file.rewind
      image_target_path = Rails.root.join('tmp', filename)
      image_target = Magick::Image.read(tmp_file.path).first
      image_target.composite(watermark, Magick::CenterGravity, Magick::CopyCompositeOp).write(image_target_path)
      tmp_file.unlink
      new_images << image_target_path
      image.purge
    end
    new_images.each do |new_image|
      images.attach(io: File.open(new_image), filename: File.basename(new_image))
    end
  end
end

app/controllers/api_controller.rb
# frozen_string_literal: true

class ApiController < ActionController::Base
  before_action :doorkeeper_authorize!
  skip_before_action :verify_authenticity_token
  respond_to :json

  private

  def current_user
    @current_user ||= User.find_by(id: doorkeeper_token[:resource_owner_id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # include DeviseTokenAuth::Concerns::SetUserByToken
  # protect_from_forgery unless: -> { request.format.json? }
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  before_action :set_active_storage_current_host

  def set_active_storage_current_host
    #ActiveStorage::Current.host = request.base_url
  end
end

app/controllers/concerns/doorkeeper_registerable.rb
module DoorkeeperRegisterable
  extend ActiveSupport::Concern

  def generate_refresh_token
    loop do
      token = SecureRandom.hex(32)
      break token unless Doorkeeper::AccessToken.exists?(refresh_token: token)
    end
  end

  def render_user(user, client_app, _token_type = 'Bearer')
    access_token = Doorkeeper::AccessToken.create(resource_owner_id: user.id,
                                                  application_id: client_app.id,
                                                  refresh_token: generate_refresh_token,
                                                  expires_in: Doorkeeper.configuration.access_token_expires_in.to_i,
                                                  scopes: '')
    {
      id: user.id,
      email: user.email,
      access_token: access_token.token,
      token_type: _token_type,
      expires_in: access_token.expires_in,
      refresh_token: access_token.refresh_token,
      created_at: access_token.created_at.to_time.to_i
    }
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def search
    @users = params[:search].present? ? User.where('email LIKE ?', "%#{params[:search]}%").order(:email) : []
    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[show edit update destroy]

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show; end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit; end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_url(@vehicle), notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def vehicle_params
    params.require(:vehicle).permit(:name, images: [])
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    # @application = Doorkeeper::Application.find_by(name: 'Web client')
    # @application = {
    #   name: @application.name,
    #   client_id: @application.uid,
    #   client_secret: @application.secret,
    # }
    @categories = Category.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def generate_graphic
    # GraphicJob.perform_later
    GraphicGeneratorService.generate
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pdf_generator_helper.rb
module PdfGeneratorHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <div class="bg-gray-50 h-screen overflow-y-scroll hide-scrollbar">
      <div class="shadow-sm border-b bg-white sticky top-0 z-50 pb-2 pt-2"><%= render "components/header" %></div>
      <main class="container mx-auto p-10">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>

  </head>

  <body data-turbo="false">
    <section class="h-screen">
      <div class="px-6 h-full text-gray-800">
        <div
          class="flex xl:justify-center lg:justify-between justify-center items-center flex-wrap h-full g-6"
        >
          <div
            class="grow-0 shrink-1 md:shrink-0 basis-auto xl:w-6/12 lg:w-6/12 md:w-9/12 mb-12 md:mb-0"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
              class="w-full"
              alt="Sample image"
            />
          </div>
          <div class="xl:ml-20 xl:w-5/12 lg:w-5/12 md:w-8/12 mb-12 md:mb-0">
          <%= yield %>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/profiles/_results.html.erb
<% if @users.present? %>
<div class="absolute -ml-[60px] m-5 border mt-4 w-[350px] bg-white">
  <div class="w-auto">
    <div class="flex justify-center -mt-[16px]">
      <%= heroicon "chevron-up", class: "stroke-gray-200 fill-white flex-no-shrink h-[25px]" %>
    </div>
  </div>
  <div class="flex justify-end">
    <div data-controller="profiles" class="m-2">
      <%= heroicon "x-circle", class: "cursor-pointer", data: { action: "click->profiles#close" } %>
    </div>
  </div>
  <ul class="max-h-[250px] overflow-y-auto">
    <% @users.each do |user| %>
      <li class="m-5">
        <%= user.email %>
      </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/profiles/search.turbo_stream.erb
<%= turbo_stream.update "results", partial: "profiles/results" %>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, class: "contents") do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <%= render partial: "vehicle_images", locals: { vehicle: vehicle} %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/vehicles/_vehicle.html.erb
<div id="<%= dom_id vehicle %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= vehicle.name %>
  </p>

  <%= render partial: "vehicle_images", locals: { vehicle: vehicle} %>

  <% if action_name != "show" %>
    <%= link_to "Show this vehicle", vehicle, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this vehicle', edit_vehicle_path(vehicle), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/vehicles/_vehicle_images.html.erb
<p class="my-5">
  <strong class="block font-medium mb-1">Image(s):</strong>
  <div class="inline flex">
    <% vehicle.images.each do |image| %>
    <%= image_tag image, class: 'm-1'%>
    <% end %>
  </div>
</p>

app/views/vehicles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing vehicle</h1>

  <%= render "form", vehicle: @vehicle %>

  <%= link_to "Show this vehicle", @vehicle, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to vehicles", vehicles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/vehicles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Vehicles</h1>
    <%= link_to 'New vehicle', new_vehicle_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="vehicles" class="min-w-full">
    <%= render @vehicles %>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New vehicle</h1>

  <%= render "form", vehicle: @vehicle %>

  <%= link_to 'Back to vehicles', vehicles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/vehicles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @vehicle %>

    <%= link_to 'Edit this vehicle', edit_vehicle_path(@vehicle), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this vehicle', vehicle_path(@vehicle), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to vehicles', vehicles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/welcome/_random.html.erb
<% 10.times.each do %>
Filme: <%=Faker::Movie.title%>
<br />
<br />
<% end %>

app/views/welcome/_results.html.erb
<% unless categories.blank? %>
  <div class="overflow-y-auto h-20 z-50 mb-2 bg-white">
    <% categories.each do |category| %>
    <div class="border border-gray-200 p-2">
    <%= category.name %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/welcome/generate_graphic.html.erb
<h1 class="">Grafico gerado pela maquina do rodrigo</h1>

app/views/welcome/index.html.erb
<div class='my-2 bg-slate-200 rounded-md p-2'>
  <h1 class="font-bold text-4xl">Welcome#index</h1>
  <p class='text-lg'>Find me in app/views/welcome/index.html.erb</p>
  <%= link_to "Generate graphic and send to email", generate_graphic_path, class: 'mt-2' %>
</div>
<%= turbo_stream_from :results_from_model %>
<%= turbo_frame_tag :results_from_model do %>
<div id="results_from_model"></div>
<% end %>

<hr>
<%= turbo_stream_from :categories_service %>
<%= turbo_frame_tag :categories_service do %>
<div id="categories">
<%= render  "random" %>
</div>
<% end %>

app/views/welcome/index.turbo_stream.erb
<%= turbo_stream.update "results", partial: "welcome/results", locals: { categories: @categories } %>